### PR TITLE
Interpolate sigma for the near wake

### PR DESCRIPTION
**Pull request by BTV25**
I went ahead and interpolated sigma for the near wake.

### CODE REVIEW

**Comment by jaredthomas68** [comment]
The math looks good and the tests pass, but it would be good if you could add a test to make sure the new interpolation is done right. Also, I'd prefer to have an option of some kind so that the pervious approach to the near wake interpolation could still be used. Your updated way should be default.

**Comment by BTV25** [comment]
Okay, let me know if I didn't follow good testing protocol, otherwise I am pretty confident in the interpolation.

**Comment by jaredthomas68** [comment]
This looks better. There are still a couple of things that need to be fixed:

1. `dx_interp` has been dropped in favor of `xd`, but this is confusing. `xd` is the point of discontinuity and `dx_interp` is our artificial x point just for interpolation. Rather than clobber `xd`, assign a new variable. There should not be any allocation cost because these are scalar values.
2. The bound has been adjusted so that there will be a discontinuity at x0 in the current code when interpolation is false. The spread will jump at `x0` from the `x0` real spread to the `xd` spread. Compare your current code to commit `d0d9ce66a996c30029b8ba7687b3d3475f178573 `. 
3. The test data needs to be cited or explained in the comments in some way so that we know where the numbers came from and that they were not just the values you got out after writing the code. We need to be testing against theory or data.

**Comment by jaredthomas68** [comment]
This looks good, but tests are failing now. Once the tests are passing we should be good to merge.

**Pull request merged**
